
export interface IDeviceType {
    id: number,
    label: string,
    ipv4Address: string,
    ipv6Address: string,
    type: string,
    ownerUserId: number,
    imageUrl: string,
    createdTime: string,
    tenantId: number,
    tenantID: string,
    country: string,
    city: string,
    platform: string,
    packageVersion: string,
    hostIP: string,
    status: string,
    groupId: number,
    deviceKey: string,
    productId: string,
    systemImage: string,
    oemImage: string,
    vin: string,
    vinUpdatedAt: string,
    canbus: string,
  }
  